#!/bin/bash
# TMJ Production Security Hardening Script
# This script prepares the codebase for production deployment

echo "🔒 Starting TMJ production security hardening..."

# Check if .env file exists
if [ ! -f ".env" ]; then
    echo "❌ .env file not found. Please create it from .env.example"
    exit 1
fi

# Load environment variables
source .env

# Check required environment variables
if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON" ]; then
    echo "❌ SUPABASE_URL and SUPABASE_ANON must be set in .env"
    exit 1
fi

echo "✅ Environment variables validated"

# Create production configuration file
cat > config/supabase.prod.js << EOF
// Production Supabase Configuration
// Auto-generated by production-hardening.sh
window.SUPABASE_URL = '$SUPABASE_URL';
window.SUPABASE_ANON = '$SUPABASE_ANON';
window.NODE_ENV = 'production';
window.ENABLE_CONSOLE_LOGS = false;
EOF

echo "✅ Production configuration created"

# Remove hardcoded credentials from HTML files
echo "🧹 Removing hardcoded credentials..."

# Backup original files
cp index.html index.html.backup 2>/dev/null || true

# Remove fallback credentials from HTML files
for html_file in *.html; do
    if [ -f "$html_file" ]; then
        echo "🔍 Processing $html_file..."
        # Remove any hardcoded Supabase URLs and keys
        sed -i.tmp '/console.warn.*fallback configuration/,/window.SUPABASE_ANON.*;/d' "$html_file" 2>/dev/null || true
        sed -i.tmp '/https.*supabase\.co/d' "$html_file" 2>/dev/null || true
        sed -i.tmp '/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9/d' "$html_file" 2>/dev/null || true
        rm -f "$html_file.tmp"
    fi
done

echo "✅ Hardcoded credentials removed"

# Update CSP headers for production
cat > .htaccess << EOF
# Security Headers for Production
<IfModule mod_headers.c>
    # Content Security Policy
    Header always set Content-Security-Policy "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' $SUPABASE_URL; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
    
    # HSTS
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    
    # Other security headers
    Header always set X-Frame-Options "DENY"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-XSS-Protection "1; mode=block"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header set Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=()"
</IfModule>

# Disable directory listing
Options -Indexes

# Hide .env and other sensitive files
<FilesMatch "^\.">
    Require all denied
</FilesMatch>

<FilesMatch "\.(env|log|txt|md)$">
    Require all denied
</FilesMatch>
EOF

echo "✅ Security headers configured"

# Create production build verification script
cat > verify-production.sh << 'EOF'
#!/bin/bash
echo "🔍 Verifying TMJ production build security..."

# Check for hardcoded credentials
if grep -r "SUPABASE_URL.*https" --include="*.html" --include="*.js" . | grep -v "config/supabase.prod.js"; then
    echo "❌ Found hardcoded credentials in source files!"
    exit 1
fi

# Check for console.log in production files
if grep -r "console\.log" --include="*.html" --include="*.js" . | grep -v "node_modules" | grep -v "verify-production.sh"; then
    echo "⚠️ Found console.log statements - consider removing for production"
fi

# Check if .env is properly excluded
if grep -q "^\.env$" .gitignore; then
    echo "✅ .env is in .gitignore"
else
    echo "❌ .env not found in .gitignore"
    exit 1
fi

# Check security scripts are present
if [ -f "config-loader.js" ] && [ -f "secure-storage.js" ] && [ -f "security-validator.js" ]; then
    echo "✅ Security scripts are present"
else
    echo "❌ Missing security scripts"
    exit 1
fi

echo "✅ Production build verification passed"
EOF

chmod +x verify-production.sh

echo "✅ Production verification script created"

# Create deployment checklist
cat > DEPLOYMENT_CHECKLIST.md << EOF
# TMJ Production Deployment Checklist

## Pre-deployment Security Checks

- [ ] Environment variables configured in .env
- [ ] Supabase keys rotated (if needed)
- [ ] Run \`./verify-production.sh\` to check security
- [ ] Test all functionality with production config
- [ ] Remove any debug console.log statements
- [ ] Verify HTTPS is configured
- [ ] Test authentication flow
- [ ] Test product CRUD operations
- [ ] Verify security headers are working

## Post-deployment Verification

- [ ] Check browser console for errors
- [ ] Test CSP headers are working (use browser dev tools)
- [ ] Verify no hardcoded credentials in page source
- [ ] Test rate limiting
- [ ] Verify secure storage is working
- [ ] Test XSS prevention
- [ ] Monitor for any security warnings

## Security Monitoring

- [ ] Set up error monitoring
- [ ] Monitor authentication failures
- [ ] Set up alerts for suspicious activity
- [ ] Regular security audits scheduled

## Rollback Plan

- [ ] Backup current production files
- [ ] Document rollback procedure
- [ ] Test rollback process

EOF

echo "✅ Deployment checklist created"

echo ""
echo "🎉 TMJ production security hardening complete!"
echo ""
echo "📋 Next steps:"
echo "1. Review and update .env with production values"
echo "2. Run './verify-production.sh' to verify security"
echo "3. Test all functionality"
echo "4. Follow DEPLOYMENT_CHECKLIST.md for deployment"
echo ""
echo "🔐 Your TMJ application is now production-ready!"
