// Production Supabase Configuration
// Auto-generated by production-hardening.sh
window.SUPABASE_URL = 'https://rmcphwbwhyfkejlpqbpt.supabase.co';
window.SUPABASE_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtY3Bod2J3aHlma2VqbHBxYnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4NDI0NTksImV4cCI6MjA5MTQxODQ1OX0.C42qKHjDdSlSo1c0sx3vNRzyeI1fP0GiNEZPFdIvaBs';
window.NODE_ENV = 'production';
window.ENABLE_CONSOLE_LOGS = false;
